LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

VPU_OUT := $(TARGET_OUT_INTERMEDIATES)/VPU_OBJ
HANTRODEC_KO = $(VPU_OUT)/ko/hantrodec.ko
HANTRODEC_DIR := $(LOCAL_PATH)
ccflags-y += -DTRACE_INCLUDE_PATH=$(src)

$(HANTRODEC_KO):
	$(MAKE_TOOL) -C $(HANTRODEC_DIR) KDIR=$(KERNEL_DIR) CROSS_COMPILE=$(CROSS_COMPILE) ARCH=$(ARCH); \
	cp $(HANTRODEC_DIR)/hantrodec.ko $(HANTRODEC_KO)

LOCAL_PREBUILT_MODULE_FILE := \
    $(HANTRODEC_KO)

LOCAL_GENERATED_SOURCES += \
    $(HANTRODEC_KO)

LOCAL_MODULE_RELATIVE_PATH := modules

LOCAL_MODULE        := hantrodec
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE  := false

include $(BUILD_PREBUILT)
