# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_LIGHT_IOPMP)	+= light-iopmp.o
obj-$(CONFIG_LIGHT_SUSPEND)	+= pm-light.o
obj-$(CONFIG_LIGHT_REBOOTMODE)	+= light_event.o
obj-$(CONFIG_LIGHT_DDR_PMU)	+= thead-ddr-pmu.o
obj-y += light_regdump.o
