override PVRSRV_DIR := services
override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override HOST_ALL_ARCH := host_x86_64 host_i386
override TARGET_PRIMARY_ARCH := target_riscv64
override TARGET_SECONDARY_ARCH :=
override TARGET_ALL_ARCH := target_riscv64
override TARGET_FORCE_32BIT :=
override PVR_ARCH := rogue
override METAG_VERSION_NEEDED := 2.8.1.0.3
override MIPS_VERSION_NEEDED := 2014.07-1
override RISCV_VERSION_NEEDED := 1.0.1
override KERNEL_COMPONENTS := srvkm drm_nulldisp
override WINDOW_SYSTEM := wayland
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := thead_linux
override SUPPORT_RGX := 1
override DISPLAY_CONTROLLER := drm_nulldisp
override PVR_SYSTEM := rgx_thead
override PVR_LOADER :=
override SORT_BRIDGE_STRUCTS := 1
override DEBUGLINK := 1
override RGX_BNC := 36.V.104.182
override SUPPORT_PHYSMEM_TEST := 1
override SUPPORT_MIPS_64K_PAGE_SIZE :=
override RGX_NUM_OS_SUPPORTED := 1
override VMM_TYPE := stub
override SUPPORT_POWMON_COMPONENT := 1
override RGX_TIMECORR_CLOCK := mono
override PDVFS_COM_HOST := 1
override PDVFS_COM_AP := 2
override PDVFS_COM_PMC := 3
override PDVFS_COM_IMG_CLKDIV := 4
override PDVFS_COM := PDVFS_COM_HOST
override PVR_GPIO_MODE_GENERAL := 1
override PVR_GPIO_MODE_POWMON_PIN := 2
override PVR_GPIO_MODE := PVR_GPIO_MODE_GENERAL
override PVR_HANDLE_BACKEND := idr
override SUPPORT_DMABUF_BRIDGE := 1
override SUPPORT_USC_BREAKPOINT := 1
override SUPPORT_DI_BRG_IMPL := 1
override SUPPORT_NATIVE_FENCE_SYNC := 1
override SUPPORT_DMA_FENCE := 1
override SUPPORT_BUFFER_SYNC := 1
ifeq ($(CONFIG_DRM_POWERVR_ROGUE_DEBUG),y)
override BUILD := debug
override PVRSRV_ENABLE_GPU_MEMORY_INFO := 1
override PVR_BUILD_TYPE := debug
else
override BUILD := release
override PVR_BUILD_TYPE := release
endif
