LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

VPU_OUT := $(TARGET_OUT_INTERMEDIATES)/VPU_OBJ
VC8000_KO = $(VPU_OUT)/ko/vc8000.ko
VC8000_DIR := $(LOCAL_PATH)

$(VC8000_KO):
	$(MAKE_TOOL) -C $(VC8000_DIR) KDIR=$(KERNEL_DIR) CROSS_COMPILE=$(CROSS_COMPILE) ARCH=$(ARCH); \
	cp $(VC8000_DIR)/vc8000.ko $(VC8000_KO)

LOCAL_PREBUILT_MODULE_FILE := \
    $(VC8000_KO)

LOCAL_GENERATED_SOURCES += \
    $(VC8000_KO)

LOCAL_MODULE_RELATIVE_PATH := modules

LOCAL_MODULE        := vc8000
LOCAL_MODULE_SUFFIX := .ko
LOCAL_MODULE_TAGS   := optional
LOCAL_MODULE_CLASS  := SHARED_LIBRARIES
LOCAL_VENDOR_MODULE := true
LOCAL_STRIP_MODULE  := false

include $(BUILD_PREBUILT)
