

#ifndef __DT_BINDINGS_LIGHT_FM_PINCTRL_DEF_H__
#define __DT_BINDINGS_LIGHT_FM_PINCTRL_DEF_H__

#define LIGHT_PIN_PULL_NONE		0
#define LIGHT_PIN_PULL_DOWN		1
#define LIGHT_PIN_PULL_UP		2

#define LIGHT_PIN_DRV_LV0		0
#define LIGHT_PIN_DRV_LV1		1
#define LIGHT_PIN_DRV_LV2		2
#define LIGHT_PIN_DRV_LV3		3
#define LIGHT_PIN_DRV_LV4		4
#define LIGHT_PIN_DRV_LV5		5
#define LIGHT_PIN_DRV_LV6		6
#define LIGHT_PIN_DRV_LV7		7
#define LIGHT_PIN_DRV_LV8		8
#define LIGHT_PIN_DRV_LV9		9
#define LIGHT_PIN_DRV_LV10		10
#define LIGHT_PIN_DRV_LV11		11
#define LIGHT_PIN_DRV_LV12		12
#define LIGHT_PIN_DRV_LV13		13
#define LIGHT_PIN_DRV_LV14		14
#define LIGHT_PIN_DRV_LV15		15

#define LIGHT_PIN_FUNC_0		0
#define LIGHT_PIN_FUNC_1		1
#define LIGHT_PIN_FUNC_2		2
#define LIGHT_PIN_FUNC_3		3
#define LIGHT_PIN_FUNC_4		4
#define LIGHT_PIN_FUNC_5		5
#define LIGHT_PIN_FUNC_6		6
#define LIGHT_PIN_FUNC_7		7

#endif // __DT_BINDINGS_LIGHT_FM_PINCTRL_DEF_H__
