/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2022 Alibaba Group Holding Limited.
 */
#ifndef _LIGHT_MISCSYS_H
#define _LIGHT_MISCSYS_H
#define CLKGEN_MISCSYS_MISCSYS_ACLK			0
#define CLKGEN_MISCSYS_USB3_DRD_CLK			1
#define CLKGEN_MISCSYS_USB3_DRD_CTRL_REF_CLK		2
#define CLKGEN_MISCSYS_USB3_DRD_PHY_REF_CLK		3
#define CLKGEN_MISCSYS_USB3_DRD_SUSPEND_CLK		4
#define CLKGEN_MISCSYS_EMMC_CLK				5
#define CLKGEN_MISCSYS_SDIO0_CLK			6
#define CLKGEN_MISCSYS_SDIO1_CLK			7
#define CLKGEN_MISCSYS_AHB2_TEESYS_HCLK			8
#define CLKGEN_MISCSYS_APB3_TEESYS_HCLK			9
#define CLKGEN_MISCSYS_AXI4_TEESYS_ACLK			10
#define CLKGEN_MISCSYS_EIP120SI_CLK			11
#define CLKGEN_MISCSYS_EIP120SII_CLK			12
#define CLKGEN_MISCSYS_EIP120SIII_CLK			13
#define CLKGEN_MISCSYS_TEEDMAC_CLK			14
#define CLKGEN_MISCSYS_EIP150B_HCLK			15
#define CLKGEN_MISCSYS_OCRAM_HCLK			16
#define CLKGEN_MISCSYS_EFUSE_PCLK			17
#define CLKGEN_MISCSYS_TEE_SYSREG_PCLK			18
#define CLKGEN_MISCSYS_CLK_END				19
#endif

